class_name RuntimeResourceManifest
extends RefCounted

# String-driven assets are preloaded so Godot cannot prune them from exports.
const RESOURCES: Array[Resource] = [
	preload("res://scenes/levels/rooms/level_01/arrival.tscn"),
	preload("res://scenes/levels/rooms/level_01/harbour_square.tscn"),
	preload("res://scenes/levels/rooms/level_01/records_alley.tscn"),
	preload("res://scenes/levels/rooms/level_01/residences_docks.tscn"),
	preload("res://scenes/levels/rooms/level_01/satyaki_waterfront.tscn"),
	preload("res://scenes/levels/rooms/level_02/lab_approach.tscn"),
	preload("res://scenes/levels/rooms/level_02/laboratory.tscn"),
	preload("res://scenes/levels/rooms/level_02/mayor_complex.tscn"),
	preload("res://scenes/levels/rooms/level_02/monkey_plaza.tscn"),
	preload("res://scenes/levels/rooms/level_02/suburb.tscn"),
	preload("res://scenes/levels/rooms/level_03/ankit_gate.tscn"),
	preload("res://scenes/levels/rooms/level_03/berry_paths.tscn"),
	preload("res://scenes/levels/rooms/level_03/chef_hut.tscn"),
	preload("res://scenes/levels/rooms/level_03/forest_entrance.tscn"),
	preload("res://scenes/levels/rooms/level_03/sharing_clearing.tscn"),
	preload("res://scenes/levels/rooms/level_04/festival_plaza.tscn"),
	preload("res://scenes/levels/rooms/level_04/hospital_reception.tscn"),
	preload("res://scenes/levels/rooms/level_04/mayor_stage.tscn"),
	preload("res://scenes/levels/rooms/level_04/pun_street.tscn"),
	preload("res://scenes/levels/rooms/level_04/serum_ward.tscn"),
	preload("res://scenes/levels/rooms/level_05/bike_route.tscn"),
	preload("res://scenes/levels/rooms/level_05/clue_chambers.tscn"),
	preload("res://scenes/levels/rooms/level_05/gummies_pub.tscn"),
	preload("res://scenes/levels/rooms/level_05/hooligan_alley.tscn"),
	preload("res://scenes/levels/rooms/level_05/mansion_foyer.tscn"),
	preload("res://scenes/levels/rooms/level_05/ruined_boulevard.tscn"),
	preload("res://scenes/levels/rooms/level_05/ruined_court.tscn"),
	preload("res://assets/level_01/backgrounds/divorcee_harbour_game.png"),
	preload("res://assets/level_01/backgrounds/rooms/arrival.png"),
	preload("res://assets/level_01/backgrounds/rooms/harbour_square.png"),
	preload("res://assets/level_01/backgrounds/rooms/records_alley.png"),
	preload("res://assets/level_01/backgrounds/rooms/residences_docks.png"),
	preload("res://assets/level_01/backgrounds/rooms/satyaki_waterfront.png"),
	preload("res://assets/level_01/sprites/battle_poojan_strength_test.png"),
	preload("res://assets/level_01/sprites/battle_satyaki_tirumal.png"),
	preload("res://assets/level_01/sprites/boss_poojan_idle.png"),
	preload("res://assets/level_01/sprites/boss_poojan_overworld.png"),
	preload("res://assets/level_01/sprites/boss_satyaki_tirumal_idle.png"),
	preload("res://assets/level_01/sprites/boss_satyaki_tirumal_overworld.png"),
	preload("res://assets/level_01/sprites/bullet_badge_warning.png"),
	preload("res://assets/level_01/sprites/bullet_broken_ring.png"),
	preload("res://assets/level_01/sprites/bullet_legal_paper.png"),
	preload("res://assets/level_01/sprites/fx_neon_flicker.png"),
	preload("res://assets/level_01/sprites/fx_paper_flutter.png"),
	preload("res://assets/level_01/sprites/fx_rain_loop.png"),
	preload("res://assets/level_01/sprites/npc_boathouse_woman_idle.png"),
	preload("res://assets/level_01/sprites/npc_dock_woman_idle.png"),
	preload("res://assets/level_01/sprites/npc_lantern_woman_idle.png"),
	preload("res://assets/level_01/sprites/npc_radio_woman_idle.png"),
	preload("res://assets/level_01/sprites/npc_raincoat_woman_idle.png"),
	preload("res://assets/level_01/sprites/prop_divorce_records.png"),
	preload("res://assets/level_01/sprites/prop_dock_route.png"),
	preload("res://assets/level_01/sprites/prop_save_notice.png"),
	preload("res://assets/level_02/backgrounds/banana_burbs_game.png"),
	preload("res://assets/level_02/backgrounds/rooms/lab_approach.png"),
	preload("res://assets/level_02/backgrounds/rooms/laboratory.png"),
	preload("res://assets/level_02/backgrounds/rooms/mayor_complex.png"),
	preload("res://assets/level_02/backgrounds/rooms/monkey_plaza.png"),
	preload("res://assets/level_02/backgrounds/rooms/suburb.png"),
	preload("res://assets/level_02/sprites/boss_deepak_reddy_idle.png"),
	preload("res://assets/level_02/sprites/boss_deepak_reddy_overworld.png"),
	preload("res://assets/level_02/sprites/boss_nitin_idle.png"),
	preload("res://assets/level_02/sprites/boss_nitin_overworld.png"),
	preload("res://assets/level_02/sprites/fx_lab_monitor_pulse.png"),
	preload("res://assets/level_02/sprites/fx_monkey_loop.png"),
	preload("res://assets/level_02/sprites/npc_happy_monkey_idle.png"),
	preload("res://assets/level_02/sprites/prop_165_files.png"),
	preload("res://assets/level_02/sprites/prop_banana_exit_gate.png"),
	preload("res://assets/level_02/sprites/prop_banana_mailbox.png"),
	preload("res://assets/level_02/sprites/prop_kfc_popcorn_box.png"),
	preload("res://assets/level_03/backgrounds/berry_barks_game.png"),
	preload("res://assets/level_03/backgrounds/rooms/ankit_gate.png"),
	preload("res://assets/level_03/backgrounds/rooms/berry_paths.png"),
	preload("res://assets/level_03/backgrounds/rooms/chef_hut.png"),
	preload("res://assets/level_03/backgrounds/rooms/forest_entrance.png"),
	preload("res://assets/level_03/backgrounds/rooms/sharing_clearing.png"),
	preload("res://assets/level_03/sprites/boss_ankit_idle.png"),
	preload("res://assets/level_03/sprites/boss_ankit_overworld.png"),
	preload("res://assets/level_03/sprites/boss_niggesh_nishal_idle.png"),
	preload("res://assets/level_03/sprites/boss_niggesh_nishal_overworld.png"),
	preload("res://assets/level_03/sprites/fx_berry_glow.png"),
	preload("res://assets/level_03/sprites/fx_mist_drift.png"),
	preload("res://assets/level_03/sprites/npc_berry_apothecary_idle.png"),
	preload("res://assets/level_03/sprites/npc_berry_picker_idle.png"),
	preload("res://assets/level_03/sprites/npc_fir_grandmother_idle.png"),
	preload("res://assets/level_03/sprites/npc_mist_ranger_idle.png"),
	preload("res://assets/level_03/sprites/prop_auticity_exit_arch.png"),
	preload("res://assets/level_03/sprites/prop_berry_cluster.png"),
	preload("res://assets/level_03/sprites/prop_berry_contract.png"),
	preload("res://assets/level_03/sprites/prop_berry_share_table.png"),
	preload("res://assets/level_03/sprites/prop_berry_watch_save.png"),
	preload("res://assets/level_04/backgrounds/auticity_game.png"),
	preload("res://assets/level_04/backgrounds/rooms/festival_plaza.png"),
	preload("res://assets/level_04/backgrounds/rooms/hospital_reception.png"),
	preload("res://assets/level_04/backgrounds/rooms/mayor_stage.png"),
	preload("res://assets/level_04/backgrounds/rooms/pun_street.png"),
	preload("res://assets/level_04/backgrounds/rooms/serum_ward.png"),
	preload("res://assets/level_04/sprites/boss_doctor_sushan_idle.png"),
	preload("res://assets/level_04/sprites/boss_doctor_sushan_overworld.png"),
	preload("res://assets/level_04/sprites/boss_mitta_idle.png"),
	preload("res://assets/level_04/sprites/boss_mitta_overworld.png"),
	preload("res://assets/level_04/sprites/fx_aeon_fireworks.png"),
	preload("res://assets/level_04/sprites/fx_fluorescent_buzz.png"),
	preload("res://assets/level_04/sprites/npc_clinic_receptionist_idle.png"),
	preload("res://assets/level_04/sprites/npc_festival_drummer_idle.png"),
	preload("res://assets/level_04/sprites/npc_neon_patient_idle.png"),
	preload("res://assets/level_04/sprites/npc_pun_vendor_idle.png"),
	preload("res://assets/level_04/sprites/prop_aeon_stage.png"),
	preload("res://assets/level_04/sprites/prop_area111_exit.png"),
	preload("res://assets/level_04/sprites/prop_hospital_records_terminal.png"),
	preload("res://assets/level_04/sprites/prop_pun_vendor_cart.png"),
	preload("res://assets/level_04/sprites/prop_save_kiosk.png"),
	preload("res://assets/level_05/backgrounds/rooms/bike_route.png"),
	preload("res://assets/level_05/backgrounds/rooms/clue_chambers.png"),
	preload("res://assets/level_05/backgrounds/rooms/gummies_pub.png"),
	preload("res://assets/level_05/backgrounds/rooms/hooligan_alley.png"),
	preload("res://assets/level_05/backgrounds/rooms/mansion_foyer.png"),
	preload("res://assets/level_05/backgrounds/rooms/ruined_boulevard.png"),
	preload("res://assets/level_05/backgrounds/rooms/ruined_court.png"),
	preload("res://assets/level_05/sprites/boss_srmt_idle.png"),
	preload("res://assets/level_05/sprites/boss_srmt_overworld.png"),
	preload("res://assets/level_05/sprites/boss_suhas_idle.png"),
	preload("res://assets/level_05/sprites/boss_suhas_overworld.png"),
	preload("res://assets/level_05/sprites/fx_club_static.png"),
	preload("res://assets/level_05/sprites/fx_musical_notes.png"),
	preload("res://assets/level_05/sprites/fx_throne_reveal.png"),
	preload("res://assets/level_05/sprites/npc_bike_mechanic_idle.png"),
	preload("res://assets/level_05/sprites/npc_ishiyoga_idle.png"),
	preload("res://assets/level_05/sprites/npc_pink_hooligan_idle.png"),
	preload("res://assets/level_05/sprites/npc_pub_keeper_idle.png"),
	preload("res://assets/level_05/sprites/npc_ruin_vendor_idle.png"),
	preload("res://assets/level_05/sprites/prop_ending_feast.png"),
	preload("res://assets/level_05/sprites/prop_gummies_bar.png"),
	preload("res://assets/level_05/sprites/prop_kfc_dungeon_gate.png"),
	preload("res://assets/level_05/sprites/prop_mansion_clue_console.png"),
	preload("res://assets/level_05/sprites/prop_musical_guitar.png"),
	preload("res://assets/level_05/sprites/prop_srmt_throne.png"),
	preload("res://assets/level_05/sprites/prop_suhas_motorcycle.png"),
	preload("res://assets/shared/audio/encounter_start.wav"),
	preload("res://assets/shared/audio/music/boss_confrontation.wav"),
	preload("res://assets/shared/audio/music/ending_feast.wav"),
	preload("res://assets/shared/audio/music/level_01_rainy_harbor_noir.wav"),
	preload("res://assets/shared/audio/music/level_02_uncanny_suburb_jingle.wav"),
	preload("res://assets/shared/audio/music/level_03_forest_mystery.wav"),
	preload("res://assets/shared/audio/music/level_04_hospital_festival_synth.wav"),
	preload("res://assets/shared/audio/music/level_05_ruined_club_court_finale.wav"),
	preload("res://assets/shared/audio/music/srmt_finale.wav"),
	preload("res://assets/shared/audio/music/title_theme.wav"),
	preload("res://assets/shared/audio/save_chime.wav"),
	preload("res://assets/shared/audio/sfx/banana_gun.wav"),
	preload("res://assets/shared/audio/sfx/battle_phase.wav"),
	preload("res://assets/shared/audio/sfx/berry_potion.wav"),
	preload("res://assets/shared/audio/sfx/boss_defeat.wav"),
	preload("res://assets/shared/audio/sfx/boss_hurt.wav"),
	preload("res://assets/shared/audio/sfx/building_break.wav"),
	preload("res://assets/shared/audio/sfx/clue_pickup.wav"),
	preload("res://assets/shared/audio/sfx/door_slam.wav"),
	preload("res://assets/shared/audio/sfx/growth_transform.wav"),
	preload("res://assets/shared/audio/sfx/guitar_note.wav"),
	preload("res://assets/shared/audio/sfx/revolver.wav"),
	preload("res://assets/shared/audio/sfx/transition_wipe.wav"),
	preload("res://assets/shared/audio/ui_select.wav"),
	preload("res://assets/shared/sprites/common_bullet.png"),
	preload("res://assets/shared/sprites/cutins/boss_intro.png"),
	preload("res://assets/shared/sprites/cutins/door_slam.png"),
	preload("res://assets/shared/sprites/cutins/growth_transform.png"),
	preload("res://assets/shared/sprites/cutins/ishiyoga_rescue.png"),
	preload("res://assets/shared/sprites/cutins/srmt_throne_reveal.png"),
	preload("res://assets/shared/sprites/cutins/weapon_unlocks.png"),
	preload("res://scenes/battle/battle_scene.tscn"),
	preload("res://scenes/ending.tscn"),
	preload("res://scenes/ui/cutscene_letterbox.tscn"),
	preload("res://scenes/ui/pause_menu.tscn"),
]


static func resource_count() -> int:
	return RESOURCES.size()


static func get_room_scenes(level_id: String) -> Array[PackedScene]:
	var ranges := {
		"level_01": Vector2i(0, 5),
		"level_02": Vector2i(5, 10),
		"level_03": Vector2i(10, 15),
		"level_04": Vector2i(15, 20),
		"level_05": Vector2i(20, 27)
	}
	var result: Array[PackedScene] = []
	var bounds: Vector2i = ranges.get(level_id, Vector2i.ZERO)
	for index in range(bounds.x, bounds.y):
		var packed := RESOURCES[index] as PackedScene
		if packed != null:
			result.append(packed)
	return result
